namespace TownOfSushi
{
    public enum MurderAttemptResult 
    {
        PerformKill,
        SuppressKill,
        BlankKill,
        DelayVampireKill,
        MirrorKill,
    }
    public enum CustomOptionType 
    {
        General,
        Impostor,
        Neutral,
        Crewmate,
        Modifier,
        NeutralKiller
    }
    public enum RoleId 
    {
        Jester,
        Mayor,
        Portalmaker,
        Engineer,
        Sheriff,
        Glitch,
        Lighter,
        Godfather,
        Mafioso,
        Janitor,
        Veteran,
        Detective,
        SerialKiller,
        TimeMaster,
        Medic,
        Swapper,
        Mystic,
        Morphling,
        Camouflager,
        Hacker,
        Tracker,
        Vampire,
        Snitch,
        Jackal,
        Sidekick,
        Eraser,
        Spy,
        Trickster,
        Cleaner,
        Warlock,
        Werewolf,
        SecurityGuard,
        Arsonist,
        BountyHunter,
        Vulture,
        Medium,
        Trapper,
        Lawyer,
        Prosecutor,
        Pursuer,
        Witch,
        Ninja,
        Thief,
        Bomber,
        Yoyo,
        Crewmate,
        Impostor,
        // Modifier ---
        Lover,
        Bait,
        Bloody,
        AntiTeleport,
        Tiebreaker,
        Sunglasses,
        Mini,
        Vip,
        Invert,
        Chameleon,
        Armored,
        Shifter
    }

    enum CustomRPC
    {
        // Main Controls

        ResetVaribles = 100,
        ShareOptions,
        ForceEnd,
        WorkaroundSetRoles,
        SetRole,
        SetModifier,
        VersionHandshake,
        UseUncheckedVent,
        UncheckedMurderPlayer,
        WerewolfMaul,
        UncheckedCmdReportDeadBody,
        UncheckedExilePlayer,
        DynamicMapOption,
        SetGameStarting,
        StopStart,

        // Role functionality

        EngineerFixLights = 120,
        EngineerFixSubmergedOxygen,
        EngineerUsedRepair,
        CleanBody,
        MedicSetShielded,
        ShieldedMurderAttempt,
        GlitchMimic,
        VeteranAlert,
        VeterenAlertKill,
        TimeMasterShield,
        TimeMasterRewindTime,
        ShifterShift,
        SwapperSwap,
        MorphlingMorph,
        CamouflagerCamouflage,
        TrackerUsedTracker,
        VampireSetBitten,
        PlaceGarlic,
        GlitchUsedHacks,
        JackalCreatesSidekick,
        SidekickPromotes,
        ErasePlayerRoles,
        SetFutureErased,
        SetFutureShifted,
        SetFutureShielded,
        SetFutureSpelled,
        PlaceNinjaTrace,
        PlacePortal,
        UsePortal,
        PlaceJackInTheBox,
        LightsOut,
        PlaceCamera,
        SealVent,
        ArsonistWin,
        GuesserShoot,
        LawyerSetTarget,
        LawyerPromotesToPursuer,
        SetBlanked,
        Bloody,
        SetFirstKill,
        Invert,
        SetTiebreak,
        SetInvisible,
        ThiefStealsRole,
        SetTrap,
        TriggerTrap,
        MayorSetVoteTwice,
        PlaceBomb,
        DefuseBomb,
        ShareRoom,
        YoyoMarkLocation,
        YoyoBlink,
        BreakArmor,
        SetGuessers,

        // Other functionality
        ShareTimer,
        ShareGhostInfo,
    }
    public enum Factions
    {
        Crewmate,
        Neutral,
        NeutralKiller,
        Impostor,
        Modifier
    }
    public enum GhostInfoTypes 
    {
        HackNoticed,
        HackOver,
        ArsonistDouse,
        BountyTarget,
        NinjaMarked,
        WarlockTarget,
        MysticInfo,
        MediumInfo,
        BlankUsed,
        DetectiveOrMedicInfo,
        VampireTimer,
        DeathReasonAndKiller,
    }
    enum CustomGameOverReason 
    {
        LoversWin = 10,
        TeamJackalWin = 11,
        MiniLose = 12,
        JesterWin = 13,
        ArsonistWin = 14,
        VultureWin = 15,
        ProsecutorWin = 16,
        GlitchWin = 17,
        WerewolfWin = 18,
        SerialKillerWin = 19,
    }

    enum WinCondition 
    {
        Default,
        LoversTeamWin,
        LoversSoloWin,
        JesterWin,
        JackalWin,
        MiniLose,
        ArsonistWin,
        VultureWin,
        AdditionalLawyerBonusWin,
        AdditionalAlivePursuerWin,
        ProsecutorWin,
        GlitchWin,
        WerewolfWin,
        SerialKillerWin
    }
}