global using TownOfSushi.Extensions;
global using AmongUs.GameOptions;
global using TownOfSushi.Roles;
global using TownOfSushi.Roles.Crewmates;
global using TownOfSushi.Roles.Modifiers;
global using TownOfSushi.Roles.Abilities;
global using TownOfSushi.CustomOption;
global using TownOfSushi.Patches;
global using TownOfSushi.Objects;
global using HarmonyLib;
global using UnityEngine;
global using System;
global using System.Linq;
global using System.Collections.Generic;
global using Reactor.Networking.Extensions;
global using System.Reflection;
global using Hazel;
global using Random = UnityEngine.Random;
global using Object = UnityEngine.Object;
global using TownOfSushi.Modules;
global using Il2CppInterop.Runtime.InteropTypes.Arrays;
global using static TownOfSushi.Utils;
global using static TownOfSushi.Roles.Role;
global using Reactor.Utilities;
global using BepInEx.Unity.IL2CPP;
global using TownOfSushi.Modules.ScreenEffects;
global using Reactor.Utilities.Extensions;